### PR TITLE
WIP: Adapt authorization to flaat rework

### PR DESCRIPTION
**Pull request by lburgey**
@BorjaEst Here are the changes I wanted to discuss.

### CODE REVIEW

**Comment by lburgey** [comment]
As the rework is not yet released, this uses a git dependency. We obviously need to change that, once the rework of flaat is released.

**Comment by BorjaEst** [comment]
As general comments:

- [ ] To be an standard extension we should solve "init_app". I would expect to do not have to subclass flaat.
- [ ] Injection of "user_infos" / "user" on query. The call of functions might impact less when using ohter extensions.
- [ ]

**Comment by BorjaEst** [comment]
Thanks a lot! 
Althoguh I would propose some changes (see above), I think these changes have a lot of potential and simplify a lot the code.

**Comment by lburgey** [comment]
> * Injection of "user_infos" / "user" on query. The call of functions might impact less when using ohter extensions.

Can you go into more detail on this one. I can't quite catch your intent.

**Comment by lburgey** [comment]
> [ ] To be an standard extension we should solve "init_app". I would expect to do not have to subclass flaat.

Yeah, this is the tricky part. To become a full flask extension we would have to prescribe, what config variables we expect, right? As flaat in itself is very flexible, with regard to what requirements you can define for users this would immediately restrict us to what can be easily expressed in a few config variables.
From my POV, having flaat as set of tools, to build your own flaat extensions is a good compromise. I mean look at the authorization class. Its pretty concise and easy to read.

**Comment by BorjaEst** [comment]
> > * Injection of "user_infos" / "user" on query. The call of functions might impact less when using ohter extensions.
> 
> Can you go into more detail on this one. I can't quite catch your intent.

Sure, this is collected from webargs:
```py
@app.route("/settings", methods=["POST"])
@use_kwargs(user_args)  # Injects keyword arguments
def user_settings(username, password, fullname, display_per_page, nickname):
    return render_template("settings.html", username=username, nickname=nickname)
```
The `@use_kwargs(user_args)` parses a schema" `user_args` so the elements of a query go direct as arguments into the function:
```
POST http://someurl.com/settings?username=spam&fullname=SpamAndEggs
```

Now, imagine that I design somethin with the following request.
```
POST http://someurl.com/path?user=spam1
```

I would have to configure the endpoint as:
```py
@app.route("/path", methods=["POST"])
@use_kwargs(post_something_schema)  # Injects keyword arguments
@auth.inject_user()
def post_something(user, user):  # <- here is the conflict
    return 201
```

You see what I mean?

**Comment by BorjaEst** [comment]
> > [ ] To be an standard extension we should solve "init_app". I would expect to do not have to subclass flaat.
> 
> Yeah, this is the tricky part. To become a full flask extension we would have to prescribe, what config variables we expect, right? 
Yes

> As flaat in itself is very flexible, with regard to what requirements you can define for users this would immediately restrict us to what can be easily expressed in a few config variables. From my POV, having flaat as set of tools, to build your own flaat extensions is a good compromise. I mean look at the authorization class. Its pretty concise and easy to read.
For terms of flexibility that is right, for terms of usability is the oposite.
Normally Flask (or any framework) users expect the tools they integrate to behave as the framework expects, then they do not have to read all about the tool, all looks familiar and testing is easier. In addition, Flask users are not Flask developers, they might not know how to apply the "extension" pattern to create their own authorization and therefore look for easier tools.

In any of the cases, what you have done is a big advance and welcome.

**Comment by lburgey** [comment]
> ```python
> def post_something(user, user):  # <- here is the conflict
>     return 201
> ```

This conflict would not happen, as you can specify which key the injected object has:
```python
class Authorization(Flaat):
[..]
def inject_user(self):
    [..]

    return self.inject_object(infos_to_object=_get_user, key="user") # <- key is specified here
```

**Comment by BorjaEst** [comment]
> > ```python
> > def post_something(user, user):  # <- here is the conflict
> >     return 201
> > ```
> 
> This conflict would not happen, as you can specify which key the injected object has:
> 
> ```python
> class Authorization(Flaat):
> [..]
> def inject_user(self):
>     [..]
> 
>     return self.inject_object(infos_to_object=_get_user, key="user") # <- key is specified here
> ```
Yes, that is a solution good :+1:

**Comment by BorjaEst** [comment]
This is merged at https://github.com/EOSC-synergy/eosc-perf-backend
Thank you @lburgey

**Pull request closed without merging**
