### PR TITLE
add exception for Aarc_g002_entitlement_Error

### PR DESCRIPTION
**Pull request by marcvs**
aarg_g002 raises errors, if something goes wrong.
Patch handles the exception

### CODE REVIEW

**Comment by TheChristophe** [comment]
Would it be possible to update the requirements.txt in the same PR?

**Comment by marcvs** [comment]
Upps. Those requirements contain "==" 
I would not do that, because this creates problems: Imagine you install two packages, one depends on 0.2.1 the other on 0.2.2, while 0.3 is up-to-date. You'll only be able to install one at a time.
Is there a particular reason for this?

I've changed the one for g002 to >= 0.3

**Comment by TheChristophe** [comment]
I don't believe there's a particular reason other than someone just ran pip freeze at one point and it never broke.

**Comment by TheChristophe** [comment]
On the note of syntax, I may change it to ~=0.3.1 later, so it stays within compatible versions. Given 0.3 itself was a breaking change, I'd like to avoid accidentally installing a 0.4 that breaks something else.

**Pull request merged**
