### PR TITLE
ci-cd for frontend and backend with reports

### PR DESCRIPTION
**Pull request by vykozlov**
[cicd] re-arrange SQA pipeline by having one config.yml and docker-compose.yml for both frontend and backend

[cicd][frontend] update SQA pipeline (frontend) with dedicated Dockerfile.cicd to start  container as a non-root user (matches jenkins uid and gid)

[cicd][frontend] update Dockerfile with optional copy of .env.local

[cicd][backend] update service_backend/tox.ini

[cicd][backend] unifying Dockerfile.cicd for CI/CD

### CODE REVIEW

**Comment by vykozlov** [comment]
The built fails due to a vulnerability very recently found in the frontend, check:
*  https://jenkins.eosc-synergy.eu/job/eosc-synergy-org/job/eosc-perf/job/ci-cd-for-frontend/8/issues/
*  https://github.com/advisories/GHSA-74fj-2j2h-c42q

the added in the PR code (concerns CI/CD only) should be fine and all added stages/CI-CD reports look correctly generated, see:
*   https://jenkins.eosc-synergy.eu/job/eosc-synergy-org/job/eosc-perf/job/ci-cd-for-frontend/
*   https://jenkins.eosc-synergy.eu/job/eosc-synergy-org/job/eosc-perf/job/ci-cd-for-frontend/8

**Comment by TheChristophe** [comment]
I cannot find what the above checks are referring to e.g. what is supposed to have failed?

**Comment by TheChristophe** [comment]
> The built fails due to a vulnerability very recently found in the frontend, check:
> 
>     * https://jenkins.eosc-synergy.eu/job/eosc-synergy-org/job/eosc-perf/job/ci-cd-for-frontend/8/issues/
> 
>     * [GHSA-74fj-2j2h-c42q](https://github.com/advisories/GHSA-74fj-2j2h-c42q)
> 
> 
> the added in the PR code (concerns CI/CD only) should be fine and all added stages/CI-CD reports look correctly generated, see:
> 
>     * https://jenkins.eosc-synergy.eu/job/eosc-synergy-org/job/eosc-perf/job/ci-cd-for-frontend/
> 
>     * https://jenkins.eosc-synergy.eu/job/eosc-synergy-org/job/eosc-perf/job/ci-cd-for-frontend/8

Unfortunately, all the jenkins.eosc-synergy.eu pages 404 for me

**Comment by TheChristophe** [comment]
Pushed a fix to issue that was failing the checks and merged into this branch

**Pull request merged**
