### PR TITLE
Add db.create_all to autoapp.py

### PR DESCRIPTION
**Pull request by BorjaEst**
Solves #156 (autostart db)

### CODE REVIEW

**Comment by BorjaEst** [comment]
- Note the database is only started when running the compose service "backend_v1" (e.g. docker-compose up backend_v1) 
- Already tested

**Comment by BorjaEst** [comment]
Do not merge get, the idea is to use alembic.
Create db does not apply the "alembic" versioning, so it is not possible to upgrade database changes in the future.

**Comment by TheChristophe** [comment]
What about setting the docker entrypoint to a script that runs flask db upgrade before launching the application?

**Comment by BorjaEst** [comment]
So the entrypoint you mention is autoapp.py is already there.
At the end was easy, just to change "create_all" by "flask_migrate.upgrade()".

Now it should work, from my local it is working. I can create new migrations and upgrade the database. I would say it is now ready to merge. Sorry for the mess.

**Comment by BorjaEst** [comment]
I am also going to update the README

**Pull request merged**
